Experiment_name: Auto_Encode
## dropout and weight_decay

# feeder
feeder: feeder.dataset.Mnist
num_workers: 2
train_feeder_args:
# test_feeder_args:
  root: data
  split: train

# train_feeder_args:
test_feeder_args:
  root: data
  split: val

# model
model: model.AE.AutoEncoder
model_args:
  out_encode: True
  

# weights: work_dir/graph_split_trans_SGD_4head2022-04-07/save_models/graph_split_trans_SGD_4head-46.pt

#optim
optim: Adam
weight_decay: 0.0001
lr: 0.001

scheduler: multiStep
scheduler_args: 
  milestones: [20, 40, 70]
  gamma: 0.1

# training 
phase: train
debug: False
device: [0]
only_train_epoch: 0
warm_up_epoch: 0
batch_size: 256
epochs: 100
nesterov: True
WeightSaveNum: 10

log_interval: 30
